### ISSUE TITLE
Kanban Board

### ISSUE THREAD

**Issue by abel-tefera** [abel-tefera/space-travellers-hub#27]
[Link to Project](https://github.com/abel-tefera/space-travellers-hub/projects/1)

We are a team of 2 members

**Comment by Owusu-Desmond** [comment]
Hi @abel-tefera AND @Lul-Abdifan , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/YYht2UTV41u1vxHTss/giphy-downsized-medium.gif"/>

## Highlights
📌 You assign project cards to collaborators :+1: ✅
📌 Great working on the setup of the project board ✅

## Required Changes ♻️
_Check the comments under the 

- [ ] Please you are missing these three cards ([[1pt] Create app and install basic dependencies - Setup (group task)](https://github.com/microverseinc/curriculum-react-redux/issues/47), [[1pt] Create website header with empty nav - Setup (group task)](https://github.com/microverseinc/curriculum-react-redux/issues/51), and [[1pt] Create basic structure for Rockets - Setup](https://github.com/microverseinc/curriculum-react-redux/issues/50)) which should make the total number of cards for group of two project kanban board be 17. But now you have only 14 cards:blush: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by abel-tefera** [comment]
Hello, @Owusu-Desmond 

Those tasks are not missing. They have been moved to the "done" column because we did those tasks. The total number of tasks remains 17.

**Comment by Owusu-Desmond** [comment]
Hi @abel-tefera, I apologize for this inconvenience, please submit it again for approval of your project :pray:

**Comment by Gambit142** [comment]
Hi @abel-tefera @Lul-Abdifan ,

## Status: Approved 🟢   

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

### Highlights
- Set up the kanban board properly ✔️ 
- Assigned every card to a member of the team ✔️ 

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
